# Generated by Django 3.2.9 on 2022-01-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_meta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meta',
            new_name='new',
        ),
    ]
