# Generated by Django 3.2.9 on 2022-01-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_rename_meta_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
